/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.java;

import com.google.common.collect.Lists;

import java.util.*;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 * To build:
 * ./gradlew build
 */
public class App {
    public static void main(String... args) {
        List<Integer> example = new ArrayList<>();
        Set<Integer> wSort = new TreeSet<>();

        Random rnd = new Random();

        for (int i = 0; i < 100; i++) {
            example.add(rnd.nextInt((100)));
        }

        for (int i : example) {
            wSort.add(i);
        }

        Set<Integer> woDubls = new HashSet<>(example);
        Integer[] arr = example.toArray(new Integer[0]);

        System.out.println("Current set: " + Arrays.toString(arr));
        System.out.println("Filtered set: " + woDubls);
        System.out.println("Sorted set: " + wSort);

    }
}
